---
title: "Multivariate viz reading"
editor: visual
---
```{r}
library(tidyverse)
```

```{r}
# Import data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date)) 
```

```{r}
# Check out the first 6 rows
# What are the units of observation?
head(weather)
```

Date, location, mintemp, maxtemp, rainfall, evaporation. 

```{r}
# How many data points do we have? 
```

2367 observations

```{r}
# What type of variables do we have?
str(weather)
```

```{r}
ggplot(weather, aes(x = temp3pm)) + 
  geom_density()
```

```{r}
# Plot 1 (no facets & starting from a density plot of temp3pm)
ggplot(weather, aes(x = temp3pm, fill = location)) + 
  geom_density(alpha = 0.5)
```

```{r}
# Plot 2 (no facets or densities)
ggplot(weather, aes(y = temp3pm, x = location)) + 
  geom_boxplot()
```

```{r}
# Plot 3 (facets)
ggplot(weather, aes(x = temp3pm, fill = location)) + 
  geom_density(alpha = 0.5) + 
  facet_wrap(~ location)
```

```{r}
# How often does it raintoday?
# Fill your geometric layer with the color blue.
ggplot(weather, aes(x = raintoday)) + 
  geom_bar(fill = "blue")
```

Today, it rains less than 500 (ml?)

```{r}
# If it does raintoday, what does this tell us about raintomorrow?
# Use your intuition first
ggplot(weather, aes(x = raintoday)) + 
  geom_bar(aes(fill = raintomorrow))
```

There will be a higher chance of no rain tomorrow if it does not rain today. 

```{r}
ggplot(weather, aes(x = raintoday, fill = raintomorrow)) + 
  geom_bar()
```

```{r}
ggplot(weather, aes(x = raintoday, fill = raintomorrow)) + 
  geom_bar(position = "dodge")
```

```{r}
ggplot(weather, aes(x = raintoday, fill = raintomorrow)) + 
  geom_bar(position = "fill")
```

```{r}
ggplot(weather, aes(y = temp3pm, x = date)) + 
  geom_point() + 
  geom_smooth(span = 0.5)
```

```{r}
ggplot(weather, aes(y = temp3pm, x = date)) + 
  geom_line()
```

```{r}
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point()
```

```{r}
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point() +
  facet_wrap(~ raintoday)
```

```{r}
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location, shape = raintoday)) + 
  geom_point()
```


```{r}
ggplot(weather, aes(y = temp3pm, x = date, color = location)) + 
  geom_line()
```

```{r}
ggplot(weather, aes(x = raintoday, fill = raintomorrow)) + 
  geom_bar(position = "fill") + 
  facet_wrap(~ location)
```

